spring.application.name=job-application-tracker-backend

spring.datasource.url = jdbc:mysql://localhost:3306/jobTrackerDb
spring.datasource.username=root
spring.datasource.password = Nayan@9766

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto = update
spring.jpa.show-sql = true
spring.jpa.properties.hibernate.format_sql=true


jwt.secretKey = ads9f6askj3h4k1hf86asdfiahkjh34a789s6df89ayshkjh3jkh786adsf78ay